# Generated by Django 5.0.3 on 2024-03-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspagepost',
            old_name='date',
            new_name='pub_date',
        ),
    ]
