# Generated by Django 5.0.4 on 2024-10-16 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_date_newspagepost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspagepost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 4, 45, 42, 555901, tzinfo=datetime.timezone.utc), verbose_name='Post date'),
        ),
    ]
