# Generated by Django 5.0.4 on 2024-10-16 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newspagepost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspagepost',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 6, 38, 29, 467989, tzinfo=datetime.timezone.utc), verbose_name='Post date'),
        ),
    ]
