# Generated by Django 5.0.4 on 2024-10-30 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newspagepost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspagepost',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
    ]
