# Generated by Django 5.0.3 on 2024-04-08 04:04

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weeks_till_booking', models.IntegerField(default=26)),
                ('time_of_day_rollover', models.TimeField(help_text='What time of day to open bookings for the day max_weeks_till_booking from now')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_beds', models.IntegerField()),
                ('bunk_beds', models.IntegerField()),
                ('max_occupants', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('double_beds'), '*', models.Value(2)), '+', models.F('bunk_beds')), output_field=models.IntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('share_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.config')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('primary_shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='config.member')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='config.config')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=128)),
                ('max_monthly_room_weeks', models.IntegerField()),
                ('start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='The season will begin at the first day of the selected month')),
                ('end_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='The season will end at the end of the last day of the prior month')),
                ('season_is_peak', models.BooleanField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='config.config')),
            ],
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type_name', models.CharField(max_length=128)),
                ('rate', models.IntegerField()),
                ('is_full_week_only', models.BooleanField()),
                ('minimum_rooms', models.IntegerField(verbose_name='Minimum number of booked rooms')),
                ('priority_rank', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, help_text='Priority booking takes when calculating costs when multiple kinds are valid.')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_types', to='config.config')),
                ('banned_rooms', models.ManyToManyField(to='config.room')),
                ('season_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_types', to='config.season')),
            ],
        ),
    ]
