# Generated by Django 5.0.4 on 2024-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='maximum_family_members',
            field=models.IntegerField(default=10, help_text='maximum authorised family members including primary shareholder'),
        ),
        migrations.AddField(
            model_name='config',
            name='number_of_rooms',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='minimum_rooms',
            field=models.IntegerField(default=0, verbose_name='Minimum number of booked rooms'),
        ),
    ]
