# Generated by Django 5.0.4 on 2024-07-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_config_maximum_family_members_config_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='max_monthly_simultaneous_rooms',
            field=models.IntegerField(blank=True, help_text='Leave blank for no limit', null=True),
        ),
    ]
