# Generated by Django 5.0.3 on 2024-04-11 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_bookingtype_banned_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_months',
            field=models.JSONField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=[]),
        ),
        migrations.AlterField(
            model_name='member',
            name='share_number',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(50, message='Cannot exceed 50 shares'), django.core.validators.MinValueValidator(1, message='Share number is less than 1')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9, 'Exceeds maximum rooms'), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bunk_beds',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='double_beds',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='The season will end at the end of the last day of the selected month'),
        ),
    ]
