# Generated by Django 5.0.3 on 2024-04-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_season_season_months_alter_member_share_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_months',
            field=models.JSONField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=list),
        ),
    ]
