# Generated by Django 5.0.4 on 2024-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_bookingtype_is_flat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='last_minute_booking_weeks',
            field=models.IntegerField(default=2, help_text='Number of weeks for last minute booking rules to apply'),
        ),
        migrations.AddField(
            model_name='config',
            name='week_start_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5, help_text='The day used to determine when a week starts'),
            preserve_default=False,
        ),
    ]
