# Generated by Django 5.0.4 on 2024-11-22 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_config_last_minute_booking_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='contact_phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='contact_phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
