# Generated by Django 5.0.4 on 2024-12-04 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_familymember_contact_phone_member_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtype',
            name='season_active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_types', to='config.season'),
        ),
    ]
