# Generated by Django 5.0.4 on 2024-12-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_bookingtype_season_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtype',
            name='banned_rooms',
            field=models.ManyToManyField(blank=True, to='config.room'),
        ),
    ]
