# Generated by Django 5.0.4 on 2024-12-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_alter_bookingtype_banned_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='max_monthly_simultaneous_rooms',
        ),
    ]
