# Generated by Django 5.0.4 on 2024-12-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_remove_season_max_monthly_simultaneous_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtype',
            name='requires_flexible_booking_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='requires_last_minute_booking_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='sets_weekly_rate_cap',
            field=models.BooleanField(default=False, help_text='Whether this fair sets the maximum weekly rate'),
        ),
        migrations.AddField(
            model_name='config',
            name='flexible_booking_period',
            field=models.IntegerField(default=13, help_text='Period to allow BookingTypes that reference requiring flexible booking periods in.'),
        ),
        migrations.AddField(
            model_name='season',
            name='requires_strict_weeks',
            field=models.BooleanField(default=False, help_text="Determines whether only 7 day periods starting on 'week start day' count as weeks."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='max_weeks_till_booking',
            field=models.IntegerField(default=26, help_text="Weeks are released in 7 day chunks by counting from 'week start day' this many weeks from the most recent start day."),
        ),
    ]
