# Generated by Django 5.0.4 on 2024-12-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_bookingtype_requires_flexible_booking_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='flexible_booking_period',
            new_name='flexible_booking_weeks',
        ),
    ]
