# Generated by Django 5.0.4 on 2024-08-30 08:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corroboree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='body',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
