# Generated by Django 5.0.4 on 2024-09-09 05:45

import corroboree.config.models
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corroboree', '0003_policypage_policiespage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(help_text='A heading within the page', max_length=128)), ('board_contacts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('member', wagtail.snippets.blocks.SnippetChooserBlock(corroboree.config.models.Member)), ('position', wagtail.blocks.CharBlock(help_text='Position on board', max_length=128)), ('contact_phone', wagtail.blocks.CharBlock(help_text='Phone number as a string', max_length=14))]))), ('responsibility', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of Responsibility', max_length=128)), ('member', wagtail.snippets.blocks.SnippetChooserBlock(corroboree.config.models.Member)), ('contact_phone', wagtail.blocks.CharBlock(help_text='Phone number as a string', max_length=14))]))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policiespage',
            name='body',
            field=wagtail.fields.StreamField([('policy', wagtail.blocks.PageChooserBlock(help_text='Choose a child page which is a policy', page_type=['corroboree.PolicyPage'])), ('section', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='A section subheading to divide kinds of policies', max_length=512)), ('intro_text', wagtail.blocks.RichTextBlock(help_text='Optional introductory text for the section', required=False))])), ('policy_with_subpolicies', wagtail.blocks.StructBlock([('policy', wagtail.blocks.PageChooserBlock(help_text='Choose a child page which is a policy', page_type=['corroboree.PolicyPage'])), ('sub_policies', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(help_text='Choose child pages of the above policy page as subpolicies', page_type=['corroboree.PolicyPage'])))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='policiespage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
