# Generated by Django 5.0.4 on 2024-11-22 05:50

import corroboree.config.models
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corroboree', '0004_contactpage_body_alter_policiespage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(help_text='A heading within the page', max_length=128)), ('board_contacts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('member', wagtail.snippets.blocks.SnippetChooserBlock(corroboree.config.models.Member)), ('position', wagtail.blocks.CharBlock(help_text='Position on board', max_length=128))]))), ('responsibility', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of Responsibility', max_length=128)), ('member', wagtail.snippets.blocks.SnippetChooserBlock(corroboree.config.models.Member))]))]),
        ),
    ]
