# Generated by Django 5.0.4 on 2024-05-01 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0007_familymember_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('other_attendees', models.JSONField(default=dict)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('IS', 'Issued'), ('PD', 'Paid'), ('FL', 'Failed'), ('RF', 'Refunded')], max_length=2)),
                ('status', models.CharField(choices=[('PR', 'In Progress'), ('SB', 'Submitted'), ('FN', 'Finalised'), ('CX', 'Cancelled')], max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='config.member')),
                ('member_in_attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='config.familymember')),
                ('rooms', models.ManyToManyField(to='config.room')),
            ],
        ),
    ]
