# Generated by Django 5.0.4 on 2024-07-05 05:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingcalendar_bookingpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpage',
            name='not_authorised_message',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
