# Generated by Django 5.0.4 on 2024-07-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingpageusersummary'),
        ('config', '0002_config_maximum_family_members_config_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecord',
            name='member_in_attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='config.familymember'),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='other_attendees',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('IS', 'Issued'), ('PD', 'Paid'), ('FL', 'Failed'), ('RF', 'Refunded')], max_length=2),
        ),
    ]
