# Generated by Django 5.0.4 on 2024-07-25 05:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingrecord_member_in_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='edit_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display when editing a booking'),
        ),
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='inprogess_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to introduce bookings that need to be completed if any exit'),
        ),
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='not_editable_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display when linked booking is not theirs or editable'),
        ),
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='upcoming_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to introduce upcoming bookings if any exist'),
        ),
    ]
