# Generated by Django 5.0.4 on 2024-07-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingpageusersummary_edit_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingpageusersummary',
            old_name='not_editable_text',
            new_name='not_found_text',
        ),
    ]
