# Generated by Django 5.0.4 on 2024-07-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_not_editable_text_bookingpageusersummary_not_found_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingpageusersummary',
            old_name='inprogess_text',
            new_name='in_progress_text',
        ),
    ]
