# Generated by Django 5.0.4 on 2024-07-30 05:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_inprogess_text_bookingpageusersummary_in_progress_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpageusersummary',
            name='intro',
        ),
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='submitted_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to introduce bookings that have been submitted but not confirmed/paid'),
        ),
    ]
