# Generated by Django 5.0.4 on 2024-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_bookingpageusersummary_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecord',
            name='payment_status',
            field=models.CharField(choices=[('IS', 'Issued'), ('PD', 'Paid'), ('FL', 'Failed'), ('RF', 'Refunded'), ('NI', 'Not Issued')], default='NI', max_length=2),
        ),
    ]
