# Generated by Django 5.0.4 on 2024-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_bookingrecord_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
