# Generated by Django 5.0.8 on 2024-10-01 05:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_bookingrecord_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='cancel_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
