# Generated by Django 5.0.4 on 2024-10-16 04:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_bookingpageusersummary_cancel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingpageusersummary',
            name='cancel_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display above the cancellation form'),
        ),
    ]
