# Generated by Django 5.0.4 on 2024-10-16 06:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_bookingrecord_paypal_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='pay_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display at the payment page'),
        ),
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='payment_error_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display if the success page is displaying an unpaid booking'),
        ),
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='payment_success_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after a successful payment'),
        ),
    ]
