# Generated by Django 5.0.4 on 2024-12-04 02:16

from django.db import migrations, models


def copy_names_to_at_creation(apps, schema_editor):
    MetaDataValue = apps.get_model('app', 'metadatavalue')
    db_alias = schema_editor.connection.alias
    from django.db.models import F
    MetaDataValue.objects.using(db_alias).all().update(
        member_name_at_creation=F('member__first_name') + ' ' + F('member__last_name')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_bookingrecord_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='member_in_attendance_name_at_creation',
            field=models.CharField(blank=True, help_text='The name of the original member who booked. Used for record keeping when shares are transferred', max_length=128),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='member_name_at_creation',
            field=models.CharField(default='default', help_text='The name of the original member who booked. Used for record keeping when shares are transferred', max_length=128),
            preserve_default=False,
        ),
    ]
