# Generated by Django 5.0.4 on 2024-12-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_bookingrecord_member_in_attendance_name_at_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrecord',
            old_name='start_date',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='bookingrecord',
            old_name='end_date',
            new_name='departure_date',
        ),
    ]
