# Generated by Django 5.0.4 on 2024-12-16 03:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_bookingpage_calendar_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcalendar',
            name='caption',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displays under the calendar'),
        ),
    ]
