# Generated by Django 5.0.4 on 2024-12-18 01:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_bookingcalendar_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpageusersummary',
            name='edit_guests_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display when editing guests'),
        ),
    ]
