# Generated by Django 5.0.4 on 2025-02-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_bookingpageusersummary_edit_guests_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='send_admin_email',
            field=models.BooleanField(default=False, help_text='Mark this True if an email should be sent indicating that an administrator created or tinkered with this booking'),
        ),
    ]
